name: Update Exchange Rates

on:
  schedule:
    # Run at minute 5 of every hour
    - cron: '5 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-rates:
    runs-on: ubuntu-latest
    steps:
      - name: Update Exchange Rates
        env:
          SITE_URL: ${{ secrets.SITE_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          response=$(curl -s -w "\n%{http_code}" -X GET "${SITE_URL}/api/cron/update-exchange-rates" \
            -H "Authorization: Bearer ${CRON_SECRET}")

          status_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')

          echo "Response body: $body"
          echo "Status code: $status_code"

          if [ "$status_code" != "200" ]; then
            echo "Error: Request failed with status $status_code"
            exit 1
          fi
